// Generated by Passport. Do not modify.
// File generated at 2/28/2026, 3:02 PM
package core

import "time"

type HostMessageType string

const (
	HostMessageTypeComponentsList           HostMessageType = "componentsList"
	HostMessageTypeGetTasksList             HostMessageType = "getTasksList"
	HostMessageTypePermissionRequest        HostMessageType = "permissionRequest"
	HostMessageTypeRespondPermission        HostMessageType = "respondPermission"
	HostMessageTypeTasksList                HostMessageType = "tasksList"
	HostMessageTypeGetComponentsList        HostMessageType = "getComponentsList"
	HostMessageTypeLogEvent                 HostMessageType = "logEvent"
	HostMessageTypeAuthorizationsList       HostMessageType = "authorizationsList"
	HostMessageTypeRequestHistory           HostMessageType = "requestHistory"
	HostMessageTypePendingPermissionList    HostMessageType = "pendingPermissionList"
	HostMessageTypeGetAuthorizationsList    HostMessageType = "getAuthorizationsList"
	HostMessageTypeGetPendingPermissionList HostMessageType = "getPendingPermissionList"
	HostMessageTypeGetRequestHistory        HostMessageType = "getRequestHistory"
	HostMessageTypeCreateAuthorization      HostMessageType = "createAuthorization"
)

type HostStatusTask struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}

type HostStatusComponent struct {
	Name      string `json:"name"`
	Version   string `json:"version"`
	IsHealthy bool   `json:"is_healthy"`
}

type HostStatusPendingPermission struct {
	Id         string     `json:"id"`
	Permission Permission `json:"permission"`
}

type HostRequestHistoryEntry struct {
	Id            int64     `json:"id"`
	Succeeded     bool      `json:"succeeded"`
	InputBody     string    `json:"input_body"`
	InputQuery    string    `json:"input_query"`
	InputHeaders  string    `json:"input_headers"`
	Output        *string   `json:"output"`
	TaskStartDate time.Time `json:"task_start_date"`
	TaskEndDate   time.Time `json:"task_end_date"`
}

type HostMessageTasksList struct {
	Tasks []HostStatusTask `json:"tasks"`
}

type HostMessageComponentsList struct {
	Components []HostStatusComponent `json:"components"`
}

type HostMessageRequestHistory struct {
	Requests []HostRequestHistoryEntry `json:"requests"`
}

type HostMessageAuthorizationsList struct {
	Authorizations []HostMessageAuthorizationCreated `json:"authorizations"`
}

type HostMessagePendingPermissionList struct {
	PendingPermissions []HostStatusPendingPermission `json:"pending_permissions"`
}

type HostMessageGetTasksList struct {
}

type HostMessageGetComponentsList struct {
}

type HostMessageGetRequestHistory struct {
}

type HostMessageGetAuthorizationsList struct {
}

type HostMessageGetPendingPermissionList struct {
}

type HostMessageCreateAuthorization struct {
	Nickname string `json:"nickname"`
}

type HostMessageAuthorizationCreated struct {
	Nickname    *string   `json:"nickname"`
	Secret      string    `json:"secret"`
	Source      string    `json:"source"`
	CreatedDate time.Time `json:"created_date"`
}

type HostMessageLogEvent struct {
	Date      time.Time `json:"date"`
	Channel   string    `json:"channel"`
	Kind      string    `json:"kind"`
	Namespace *string   `json:"namespace"`
	Message   string    `json:"message"`
	Payload   *string   `json:"payload"`
}

type HostMessageRequestPermission struct {
	Permission Permission `json:"permission"`
}

type HostMessageRespondPermission struct {
	Approve bool `json:"approve"`
}
