// Generated by Passport. Do not modify.
// File generated at 2/28/2026, 10:11 AM
package core
import "time"
type HostMessageType string

const (
    HostMessageTypeHelloAck HostMessageType = "helloAck"
	HostMessageTypeAuthorizationCreate HostMessageType = "authorizationCreate"
	HostMessageTypeEventReceived HostMessageType = "eventReceived"
	HostMessageTypeSubscribeLogs HostMessageType = "subscribeLogs"
	HostMessageTypeSubscribeLogsAck HostMessageType = "subscribeLogsAck"
	HostMessageTypeAuthorizationCreated HostMessageType = "authorizationCreated"
	HostMessageTypeError HostMessageType = "error"
	HostMessageTypeHello HostMessageType = "hello"
)

type HostMessage struct {
    Id string `json:"id"`
	Type HostMessageType `json:"type"`
	Payload HostMessagePayload `json:"payload"`
}

type HostMessagePayload struct {
    Hello *HostMessageHello `json:"hello"`
	HelloAck *HostMessageHelloAck `json:"hello_ack"`
	SubscribeLogs *HostMessageSubscribeLogs `json:"subscribe_logs"`
	SubscribeLogsAck *HostMessageSubscribeLogsAck `json:"subscribe_logs_ack"`
	AuthorizationCreate *HostMessageAuthorizationCreate `json:"authorization_create"`
	AuthorizationCreated *HostMessageAuthorizationCreated `json:"authorization_created"`
	EventReceived *HostMessageEventReceived `json:"event_received"`
	Error *HostMessageError `json:"error"`
}

type HostMessageHello struct {
    ProtocolVersion string `json:"protocol_version"`
	ClientName string `json:"client_name"`
}

type HostMessageHelloAck struct {
    ProtocolVersion string `json:"protocol_version"`
	ServerName string `json:"server_name"`
}

type HostMessageSubscribeLogs struct {
    Tail int64 `json:"tail"`
}

type HostMessageSubscribeLogsAck struct {
    ReplayCount int64 `json:"replay_count"`
}

type HostMessageAuthorizationCreate struct {
    Nickname string `json:"nickname"`
}

type HostMessageAuthorizationCreated struct {
    Nickname *string `json:"nickname"`
	Secret string `json:"secret"`
	Source string `json:"source"`
	CreatedDate time.Time `json:"created_date"`
}

type HostMessageEventReceived struct {
    Date time.Time `json:"date"`
	Channel string `json:"channel"`
	Kind string `json:"kind"`
	Namespace *string `json:"namespace"`
	Message string `json:"message"`
	Payload *string `json:"payload"`
}

type HostMessageError struct {
    Code string `json:"code"`
	Message string `json:"message"`
}

