// Generated by Passport. Do not modify.
// File generated at 3/4/2026, 8:22 PM
package core
import "database/sql"
import "time"
type PermissionAction string

const (
    PermissionActionReadFile PermissionAction = "readFile"
)

type Permission struct {
    Container string `json:"container"`
	Action PermissionAction `json:"action"`
	Scope *string `json:"scope"`
}


type queryable interface {
    Query(query string, args ...interface{}) (*sql.Rows, error)
}
type TaskRun struct {
    Id int64 `json:"id"`
	Succeeded bool `json:"succeeded"`
	InputBody string `json:"input_body"`
	InputQuery string `json:"input_query"`
	InputHeaders string `json:"input_headers"`
	Output *string `json:"output"`
	TaskStartDate time.Time `json:"task_start_date"`
	TaskEndDate time.Time `json:"task_end_date"`
}

func ScanTaskRun(rows *sql.Rows, record *TaskRun) error {
    return rows.Scan(&record.Id, &record.Succeeded, &record.InputBody, &record.InputQuery, &record.InputHeaders, &record.Output, &record.TaskStartDate, &record.TaskEndDate)
}

func CreateTaskRun(db queryable, succeeded bool, input_body string, input_query string, input_headers string, output *string, task_start_date time.Time, task_end_date time.Time) (*TaskRun, error) {
    rows, err := db.Query("INSERT INTO task_run (succeeded, input_body, input_query, input_headers, output, task_start_date, task_end_date) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7) RETURNING *", succeeded, input_body, input_query, input_headers, output, task_start_date, task_end_date)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record TaskRun
        err := ScanTaskRun(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

type StorageRow struct {
    Id int64 `json:"id"`
	CreatedDate time.Time `json:"created_date"`
	ModifiedDate time.Time `json:"modified_date"`
	Namespace string `json:"namespace"`
	Key string `json:"key"`
	Value string `json:"value"`
}

func ScanStorageRow(rows *sql.Rows, record *StorageRow) error {
    return rows.Scan(&record.Id, &record.CreatedDate, &record.ModifiedDate, &record.Namespace, &record.Key, &record.Value)
}

func CreateStorageRow(db queryable, namespace string, key string, value string) (*StorageRow, error) {
    rows, err := db.Query("INSERT INTO kv_storage (namespace, key, value) VALUES (?1, ?2, ?3) RETURNING *", namespace, key, value)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record StorageRow
        err := ScanStorageRow(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

func UpdateStorageRow(db queryable, _namespace string, _key string, _value string) (*StorageRow, error) {
    rows, err := db.Query("UPDATE kv_storage SET modified_date = CURRENT_TIMESTAMP, value = ?3 WHERE namespace = ?1 AND key = ?2 RETURNING *", _namespace, _key, _value)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record StorageRow
        err := ScanStorageRow(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

func GetStorageRow(db queryable, _namespace string, _key string) (*StorageRow, error) {
    rows, err := db.Query("SELECT kv_storage.id AS id, kv_storage.created_date AS created_date, kv_storage.modified_date AS modified_date, kv_storage.namespace AS namespace, kv_storage.key AS key, kv_storage.value AS value FROM kv_storage WHERE kv_storage.key = ?2 AND kv_storage.namespace = ?1 LIMIT 1", _namespace, _key)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record StorageRow
        err := ScanStorageRow(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

type StorageRowKeyNames struct {
    Namespace string `json:"namespace"`
	Key string `json:"key"`
}

func ScanStorageRowKeyNames(rows *sql.Rows, record *StorageRowKeyNames) error {
    return rows.Scan(&record.Namespace, &record.Key)
}

func GetStorageRowKeyNamesInNamespace(db queryable, _namespace string) ([]StorageRowKeyNames, error) {
    rows, err := db.Query("SELECT kv_storage.namespace AS namespace, kv_storage.key AS key FROM kv_storage WHERE kv_storage.namespace = ?1", _namespace)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    records := make([]StorageRowKeyNames, 0)
    for rows.Next() {
        var record StorageRowKeyNames
        err := ScanStorageRowKeyNames(rows, &record)
        if err != nil {
            return nil, err
        }
        records = append(records, record)
    }
    return records, nil
}

type EntityRow struct {
    Id int64 `json:"id"`
	CreatedDate time.Time `json:"created_date"`
	ModifiedDate time.Time `json:"modified_date"`
	Namespace string `json:"namespace"`
	Kind string `json:"kind"`
	Value string `json:"value"`
}

func ScanEntityRow(rows *sql.Rows, record *EntityRow) error {
    return rows.Scan(&record.Id, &record.CreatedDate, &record.ModifiedDate, &record.Namespace, &record.Kind, &record.Value)
}

func CreateEntityRow(db queryable, namespace string, kind string, value string) (*EntityRow, error) {
    rows, err := db.Query("INSERT INTO entity_row (namespace, kind, value) VALUES (?1, ?2, ?3) RETURNING *", namespace, kind, value)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record EntityRow
        err := ScanEntityRow(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

func UpdateEntityRow(db queryable, _namespace string, _kind string, _id int64, _value string) ([]EntityRow, error) {
    rows, err := db.Query("UPDATE entity_row SET value = ?4 WHERE namespace = ?1 AND kind = ?2 AND id = ?3 RETURNING *", _namespace, _kind, _id, _value)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    records := make([]EntityRow, 0)
    for rows.Next() {
        var record EntityRow
        err := ScanEntityRow(rows, &record)
        if err != nil {
            return nil, err
        }
        records = append(records, record)
    }
    return records, nil
}

func GetEntityRow(db queryable, _namespace string, _kind string, _id int64) (*EntityRow, error) {
    rows, err := db.Query("SELECT entity_row.id AS id, entity_row.created_date AS created_date, entity_row.modified_date AS modified_date, entity_row.namespace AS namespace, entity_row.kind AS kind, entity_row.value AS value FROM entity_row WHERE entity_row.namespace = ?1 AND entity_row.kind = ?2 AND entity_row.id = ?3 LIMIT 1", _namespace, _kind, _id)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record EntityRow
        err := ScanEntityRow(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

func DeleteEntityRow(db queryable, _namespace string, _kind string, _id int64) ([]EntityRow, error) {
    rows, err := db.Query("WITH delete_result AS (DELETE FROM entity_row WHERE namespace = ?1 AND kind = ?2 AND id = ?3 RETURNING *) SELECT delete_result.id AS id, delete_result.created_date AS created_date, delete_result.modified_date AS modified_date, delete_result.namespace AS namespace, delete_result.kind AS kind, delete_result.value AS value FROM delete_result ", _namespace, _kind, _id)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    records := make([]EntityRow, 0)
    for rows.Next() {
        var record EntityRow
        err := ScanEntityRow(rows, &record)
        if err != nil {
            return nil, err
        }
        records = append(records, record)
    }
    return records, nil
}

func GetInNamespace(db queryable, _namespace string, _kind string) ([]EntityRow, error) {
    rows, err := db.Query("SELECT entity_row.id AS id, entity_row.created_date AS created_date, entity_row.modified_date AS modified_date, entity_row.namespace AS namespace, entity_row.kind AS kind, entity_row.value AS value FROM entity_row WHERE entity_row.namespace = ?1 AND entity_row.kind = ?2", _namespace, _kind)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    records := make([]EntityRow, 0)
    for rows.Next() {
        var record EntityRow
        err := ScanEntityRow(rows, &record)
        if err != nil {
            return nil, err
        }
        records = append(records, record)
    }
    return records, nil
}

type Authorization struct {
    Id int64 `json:"id"`
	CreatedDate time.Time `json:"created_date"`
	LastUsedDate time.Time `json:"last_used_date"`
	Nickname *string `json:"nickname"`
	Secret string `json:"secret"`
	Active bool `json:"active"`
	Source string `json:"source"`
}

func ScanAuthorization(rows *sql.Rows, record *Authorization) error {
    return rows.Scan(&record.Id, &record.CreatedDate, &record.LastUsedDate, &record.Nickname, &record.Secret, &record.Active, &record.Source)
}

func CreateAuthorization(db queryable, nickname *string, secret string, source string) (*Authorization, error) {
    rows, err := db.Query("INSERT INTO authorization (nickname, secret, source) VALUES (?1, ?2, ?3) RETURNING *", nickname, secret, source)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record Authorization
        err := ScanAuthorization(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

func UseAuthorization(db queryable, _secret string) (*Authorization, error) {
    rows, err := db.Query("UPDATE authorization SET last_used_date = CURRENT_TIMESTAMP WHERE secret = ?1 RETURNING *", _secret)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    if rows.Next() {
        var record Authorization
        err := ScanAuthorization(rows, &record)
        if err != nil {
            return nil, err
        }
        return &record, nil
    }
    return nil, nil
}

func GetAuthorizations(db queryable) ([]Authorization, error) {
    rows, err := db.Query("SELECT authorization.id AS id, authorization.created_date AS created_date, authorization.last_used_date AS last_used_date, authorization.nickname AS nickname, authorization.secret AS secret, authorization.active AS active, authorization.source AS source FROM authorization ")
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    records := make([]Authorization, 0)
    for rows.Next() {
        var record Authorization
        err := ScanAuthorization(rows, &record)
        if err != nil {
            return nil, err
        }
        records = append(records, record)
    }
    return records, nil
}

