// Generated by Passport. Do not modify.
// File generated at 2/23/2026, 4:13 PM
package component

type ComponentMessageType string

const (
    ComponentMessageTypeSetup ComponentMessageType = "setup"
	ComponentMessageTypeHello ComponentMessageType = "hello"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
	ComponentMessageTypeGetValueResponse ComponentMessageType = "getValueResponse"
	ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeGetValueRequest ComponentMessageType = "getValueRequest"
	ComponentMessageTypeStoreValueRequest ComponentMessageType = "storeValueRequest"
	ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeStoreValueResponse ComponentMessageType = "storeValueResponse"
)

