// Generated by Passport. Do not modify.
// File generated at 2/23/2026, 5:49 PM
package component

type ComponentMessageType string

const (
    ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeStoreValueRequest ComponentMessageType = "storeValueRequest"
	ComponentMessageTypeHello ComponentMessageType = "hello"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
	ComponentMessageTypeGetValueRequest ComponentMessageType = "getValueRequest"
	ComponentMessageTypeSetup ComponentMessageType = "setup"
	ComponentMessageTypeGetValueResponse ComponentMessageType = "getValueResponse"
	ComponentMessageTypeStoreValueResponse ComponentMessageType = "storeValueResponse"
)

