// Generated by Passport. Do not modify.
// File generated at 2/21/2026, 8:32 AM
package component

type ComponentMessageType string

const (
    ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeInitialize ComponentMessageType = "initialize"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
	ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeLog ComponentMessageType = "log"
	ComponentMessageTypeError ComponentMessageType = "error"
)

