// Generated by Passport. Do not modify.
// File generated at 2/20/2026, 4:11 PM
package component

type ComponentMessageType string

const (
    ComponentMessageTypeError ComponentMessageType = "error"
	ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
	ComponentMessageTypeLog ComponentMessageType = "log"
	ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeInitialize ComponentMessageType = "initialize"
)

type ComponentReadyMessage struct {
    Name string `json:"name"`
	Version string `json:"version"`
}

