// Generated by Passport. Do not modify.
// File generated at 3/9/2026, 5:59 PM
package hostio
import "time"
type EventKind string

const (
    EventKindTaskRegistered EventKind = "taskRegistered"
	EventKindComponentRegistered EventKind = "componentRegistered"
	EventKindTaskTriggered EventKind = "taskTriggered"
)

type EventTaskRegisterPayload struct {
    Name string `json:"name"`
	Url string `json:"url"`
}

type EventComponentRegisteredPayload struct {
    Name string `json:"name"`
	Version string `json:"version"`
	Suceeded bool `json:"suceeded"`
	Path string `json:"path"`
	Error *string `json:"error"`
}

type EventTaskTriggeredPayload struct {
    Id string `json:"id"`
	Name string `json:"name"`
	Date time.Time `json:"date"`
}

