// Generated by Passport. Do not modify.
// File generated at 3/9/2026, 4:48 PM
package hostio
import "time"
type HostMessageType string

const (
    HostMessageTypeAuthorizationsList HostMessageType = "authorizationsList"
	HostMessageTypeDeleteAuthorization HostMessageType = "deleteAuthorization"
	HostMessageTypeCreateAuthorization HostMessageType = "createAuthorization"
	HostMessageTypeCompleteOauth HostMessageType = "completeOauth"
	HostMessageTypeTaskRegistered HostMessageType = "taskRegistered"
	HostMessageTypeCompleteSecret HostMessageType = "completeSecret"
	HostMessageTypeTaskTriggered HostMessageType = "taskTriggered"
	HostMessageTypePermissionRequest HostMessageType = "permissionRequest"
	HostMessageTypeLogEvent HostMessageType = "logEvent"
	HostMessageTypeRequestSecret HostMessageType = "requestSecret"
	HostMessageTypeGetAuthorizationsList HostMessageType = "getAuthorizationsList"
	HostMessageTypeRequestOauth HostMessageType = "requestOauth"
	HostMessageTypeInitialize HostMessageType = "initialize"
	HostMessageTypeRespondPermission HostMessageType = "respondPermission"
	HostMessageTypeComponentRegistered HostMessageType = "componentRegistered"
)

type HostMessageAuthorizationsList struct {
    Authorizations []HostMessageAuthorizationCreated `json:"authorizations"`
}

type HostMessageTaskRegistered struct {
    Name string `json:"name"`
	Url string `json:"url"`
}

type HostMessageComponentRegistered struct {
    Name string `json:"name"`
	Version string `json:"version"`
	Suceeded bool `json:"suceeded"`
	Path string `json:"path"`
	Error *string `json:"error"`
}

type HostMessageTaskTriggered struct {
    Id string `json:"id"`
	Name string `json:"name"`
	Date time.Time `json:"date"`
}

type HostMessageGetAuthorizationsList struct {
    
}

type HostMessageCreateAuthorization struct {
    Nickname string `json:"nickname"`
}

type HostMessageDeleteAuthorization struct {
    Secret string `json:"secret"`
}

type HostMessageAuthorizationCreated struct {
    Nickname *string `json:"nickname"`
	Secret string `json:"secret"`
	Source string `json:"source"`
	CreatedDate time.Time `json:"created_date"`
}

type HostMessageLogEvent struct {
    Kind string `json:"kind"`
	Namespace string `json:"namespace"`
	Message string `json:"message"`
}

type HostMessageRequestPermission struct {
    Permission Permission `json:"permission"`
}

type HostMessageRespondPermission struct {
    Approve bool `json:"approve"`
}

type HostMessageRequestOauth struct {
    Namespace string `json:"namespace"`
	Url string `json:"url"`
	Destination string `json:"destination"`
}

type HostMessageCompleteOauth struct {
    Url string `json:"url"`
}

type HostMessageRequestSecret struct {
    Namespace string `json:"namespace"`
	Prompt string `json:"prompt"`
}

type HostMessageCompleteSecret struct {
    Secret string `json:"secret"`
}

