BEGIN;

DROP TABLE IF EXISTS task_run;
DROP TABLE IF EXISTS kv_storage;
DROP TABLE IF EXISTS entity_row;
DROP TABLE IF EXISTS authorization;


CREATE TABLE task_run (
    id INTEGER NOT NULL PRIMARY KEY,
	succeeded BOOLEAN NOT NULL,
	input_body TEXT NOT NULL,
	input_query TEXT NOT NULL,
	input_headers TEXT NOT NULL,
	output TEXT,
	task_start_date DATETIME NOT NULL,
	task_end_date DATETIME NOT NULL
);
CREATE TABLE kv_storage (
    id INTEGER NOT NULL PRIMARY KEY,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	namespace TEXT NOT NULL,
	key TEXT NOT NULL,
	value TEXT NOT NULL
);
CREATE TABLE entity_row (
    id INTEGER NOT NULL PRIMARY KEY,
	created_date DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
	namespace TEXT NOT NULL,
	kind TEXT NOT NULL,
	value TEXT NOT NULL
);
CREATE TABLE authorization (
    id INTEGER NOT NULL PRIMARY KEY,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_used_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	nickname TEXT,
	secret TEXT NOT NULL,
	active BOOLEAN NOT NULL DEFAULT 1,
	source TEXT NOT NULL
);


COMMIT;