// Generated by Passport. Do not modify.
// File generated at 3/9/2026, 12:53 PM
import Foundation
public enum PermissionAction: String, Codable, Sendable {
	case executeCommandLine = "executeCommandLine"
	case launchUrl = "launchUrl"
	case readFile = "readFile"
}
public enum HostMessageType: String, Codable, Sendable {
	case completeOauth = "completeOauth"
	case requestSecret = "requestSecret"
	case taskRegistered = "taskRegistered"
	case respondPermission = "respondPermission"
	case requestOauth = "requestOauth"
	case initialize = "initialize"
	case deleteAuthorization = "deleteAuthorization"
	case taskTriggered = "taskTriggered"
	case logEvent = "logEvent"
	case completeSecret = "completeSecret"
	case permissionRequest = "permissionRequest"
	case createAuthorization = "createAuthorization"
	case componentRegistered = "componentRegistered"
	case getAuthorizationsList = "getAuthorizationsList"
	case authorizationsList = "authorizationsList"
}
public struct Permission: Codable, Sendable {
	let container: String
	let action: PermissionAction
	let scope: String

    public init(container: String, action: PermissionAction, scope: String) {
        self.container = container
		self.action = action
		self.scope = scope
    }
}
public struct HostMessageAuthorizationsList: Codable, Sendable {
	let authorizations: [HostMessageAuthorizationCreated]

    public init(authorizations: [HostMessageAuthorizationCreated]) {
        self.authorizations = authorizations
    }
}
public struct HostMessageTaskRegistered: Codable, Sendable {
	let name: String
	let url: String

    public init(name: String, url: String) {
        self.name = name
		self.url = url
    }
}
public struct HostMessageComponentRegistered: Codable, Sendable {
	let name: String
	let version: String
	let suceeded: Bool
	let path: String
	let error: String?

    public init(name: String, version: String, suceeded: Bool, path: String, error: String?) {
        self.name = name
		self.version = version
		self.suceeded = suceeded
		self.path = path
		self.error = error
    }
}
public struct HostMessageTaskTriggered: Codable, Sendable {
	let id: String
	let name: String
	let date: Date

    public init(id: String, name: String, date: Date) {
        self.id = id
		self.name = name
		self.date = date
    }
}
public struct HostMessageGetAuthorizationsList: Codable, Sendable {
	

    public init() {
        
    }
}
public struct HostMessageCreateAuthorization: Codable, Sendable {
	let nickname: String

    public init(nickname: String) {
        self.nickname = nickname
    }
}
public struct HostMessageDeleteAuthorization: Codable, Sendable {
	let secret: String

    public init(secret: String) {
        self.secret = secret
    }
}
public struct HostMessageAuthorizationCreated: Codable, Sendable {
	let nickname: String?
	let secret: String
	let source: String
	let createdDate: Date

    public init(nickname: String?, secret: String, source: String, createdDate: Date) {
        self.nickname = nickname
		self.secret = secret
		self.source = source
		self.createdDate = createdDate
    }
}
public struct HostMessageLogEvent: Codable, Sendable {
	let kind: String
	let namespace: String
	let message: String

    public init(kind: String, namespace: String, message: String) {
        self.kind = kind
		self.namespace = namespace
		self.message = message
    }
}
public struct HostMessageRequestPermission: Codable, Sendable {
	let permission: Permission

    public init(permission: Permission) {
        self.permission = permission
    }
}
public struct HostMessageRespondPermission: Codable, Sendable {
	let approve: Bool

    public init(approve: Bool) {
        self.approve = approve
    }
}
public struct HostMessageRequestOauth: Codable, Sendable {
	let namespace: String
	let url: String
	let destination: String

    public init(namespace: String, url: String, destination: String) {
        self.namespace = namespace
		self.url = url
		self.destination = destination
    }
}
public struct HostMessageCompleteOauth: Codable, Sendable {
	let url: String

    public init(url: String) {
        self.url = url
    }
}
public struct HostMessageRequestSecret: Codable, Sendable {
	let namespace: String
	let prompt: String

    public init(namespace: String, prompt: String) {
        self.namespace = namespace
		self.prompt = prompt
    }
}
public struct HostMessageCompleteSecret: Codable, Sendable {
	let secret: String

    public init(secret: String) {
        self.secret = secret
    }
}
