// Generated by Passport. Do not modify.
// File generated at 3/4/2026, 8:22 PM
package componentipc

type ComponentMessageType string

const (
    ComponentMessageTypeStoreKeychainRequest ComponentMessageType = "storeKeychainRequest"
	ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeHello ComponentMessageType = "hello"
	ComponentMessageTypeStoreValueRequest ComponentMessageType = "storeValueRequest"
	ComponentMessageTypeGetKeychainRequest ComponentMessageType = "getKeychainRequest"
	ComponentMessageTypeGetKeychainResponse ComponentMessageType = "getKeychainResponse"
	ComponentMessageTypeSetup ComponentMessageType = "setup"
	ComponentMessageTypeSendTrigger ComponentMessageType = "sendTrigger"
	ComponentMessageTypeGetValueRequest ComponentMessageType = "getValueRequest"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
	ComponentMessageTypeLog ComponentMessageType = "log"
	ComponentMessageTypeGetValueResponse ComponentMessageType = "getValueResponse"
)

