// Generated by Passport. Do not modify.
// File generated at 2/27/2026, 12:06 PM
package componentipc

type MessageType string

const (
	MessageTypeSetup                MessageType = "setup"
	MessageTypeGetValueRequest      MessageType = "getValueRequest"
	MessageTypeRet                  MessageType = "ret"
	MessageTypeGetValueResponse     MessageType = "getValueResponse"
	MessageTypeStoreKeychainRequest MessageType = "storeKeychainRequest"
	MessageTypeGetKeychainResponse  MessageType = "getKeychainResponse"
	MessageTypeStoreValueRequest    MessageType = "storeValueRequest"
	MessageTypeExecute              MessageType = "execute"
	MessageTypeGetKeychainRequest   MessageType = "getKeychainRequest"
	MessageTypeLog                  MessageType = "log"
	MessageTypeReady                MessageType = "ready"
	MessageTypeHello                MessageType = "hello"
)
