// Generated by Passport. Do not modify.
// File generated at 2/28/2026, 10:11 AM
package componentipc

type MessageType string

const (
    MessageTypeStoreValueRequest MessageType = "storeValueRequest"
	MessageTypeLog MessageType = "log"
	MessageTypeGetKeychainRequest MessageType = "getKeychainRequest"
	MessageTypeSetup MessageType = "setup"
	MessageTypeGetKeychainResponse MessageType = "getKeychainResponse"
	MessageTypeHello MessageType = "hello"
	MessageTypeExecute MessageType = "execute"
	MessageTypeGetValueRequest MessageType = "getValueRequest"
	MessageTypeRet MessageType = "ret"
	MessageTypeStoreKeychainRequest MessageType = "storeKeychainRequest"
	MessageTypeGetValueResponse MessageType = "getValueResponse"
	MessageTypeReady MessageType = "ready"
)

