// Generated by Passport. Do not modify.
// File generated at 3/8/2026, 7:20 PM
package componentipc

type ComponentMessageType string

const (
    ComponentMessageTypeLaunchUrlResponse ComponentMessageType = "launchUrlResponse"
	ComponentMessageTypeLog ComponentMessageType = "log"
	ComponentMessageTypeSetup ComponentMessageType = "setup"
	ComponentMessageTypeRequestSecretAuthentication ComponentMessageType = "requestSecretAuthentication"
	ComponentMessageTypeHello ComponentMessageType = "hello"
	ComponentMessageTypeCompleteSecretAuthentication ComponentMessageType = "completeSecretAuthentication"
	ComponentMessageTypeExecuteProgramRequest ComponentMessageType = "executeProgramRequest"
	ComponentMessageTypeGetValueResponse ComponentMessageType = "getValueResponse"
	ComponentMessageTypeExecuteProgramResponse ComponentMessageType = "executeProgramResponse"
	ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeStoreValueRequest ComponentMessageType = "storeValueRequest"
	ComponentMessageTypeGetValueRequest ComponentMessageType = "getValueRequest"
	ComponentMessageTypeStoreKeychainRequest ComponentMessageType = "storeKeychainRequest"
	ComponentMessageTypeGetKeychainResponse ComponentMessageType = "getKeychainResponse"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
	ComponentMessageTypeSendTrigger ComponentMessageType = "sendTrigger"
	ComponentMessageTypeRequestOauthAuthentication ComponentMessageType = "requestOauthAuthentication"
	ComponentMessageTypeGetKeychainRequest ComponentMessageType = "getKeychainRequest"
	ComponentMessageTypeCompleteOauthAuthentication ComponentMessageType = "completeOauthAuthentication"
	ComponentMessageTypeLaunchUrlRequest ComponentMessageType = "launchUrlRequest"
)

