// Generated by Passport. Do not modify.
// File generated at 3/13/2026, 9:42 AM
package componentipc

type ComponentMessageType string

const (
    ComponentMessageTypeRequestOauthAuthentication ComponentMessageType = "requestOauthAuthentication"
	ComponentMessageTypeGetValueResponse ComponentMessageType = "getValueResponse"
	ComponentMessageTypeLog ComponentMessageType = "log"
	ComponentMessageTypeStoreKeychainRequest ComponentMessageType = "storeKeychainRequest"
	ComponentMessageTypeCompleteSecretAuthentication ComponentMessageType = "completeSecretAuthentication"
	ComponentMessageTypeReadFileRequest ComponentMessageType = "readFileRequest"
	ComponentMessageTypeRequestSecretAuthentication ComponentMessageType = "requestSecretAuthentication"
	ComponentMessageTypeHello ComponentMessageType = "hello"
	ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeLaunchUrlRequest ComponentMessageType = "launchUrlRequest"
	ComponentMessageTypeStoreValueRequest ComponentMessageType = "storeValueRequest"
	ComponentMessageTypeExecuteProgramStartedResponse ComponentMessageType = "executeProgramStartedResponse"
	ComponentMessageTypeExecuteProgramRequest ComponentMessageType = "executeProgramRequest"
	ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeSendTrigger ComponentMessageType = "sendTrigger"
	ComponentMessageTypeExecuteProgramResponse ComponentMessageType = "executeProgramResponse"
	ComponentMessageTypeLaunchUrlResponse ComponentMessageType = "launchUrlResponse"
	ComponentMessageTypeGetKeychainResponse ComponentMessageType = "getKeychainResponse"
	ComponentMessageTypeGetKeychainRequest ComponentMessageType = "getKeychainRequest"
	ComponentMessageTypeCompleteOauthAuthentication ComponentMessageType = "completeOauthAuthentication"
	ComponentMessageTypeGetValueRequest ComponentMessageType = "getValueRequest"
	ComponentMessageTypeReadFileResponse ComponentMessageType = "readFileResponse"
	ComponentMessageTypeSetup ComponentMessageType = "setup"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
)

