// Generated by Passport. Do not modify.
// File generated at 3/9/2026, 12:53 PM
package componentipc

type ComponentMessageType string

const (
    ComponentMessageTypeRequestSecretAuthentication ComponentMessageType = "requestSecretAuthentication"
	ComponentMessageTypeGetValueRequest ComponentMessageType = "getValueRequest"
	ComponentMessageTypeGetValueResponse ComponentMessageType = "getValueResponse"
	ComponentMessageTypeRequestOauthAuthentication ComponentMessageType = "requestOauthAuthentication"
	ComponentMessageTypeGetKeychainRequest ComponentMessageType = "getKeychainRequest"
	ComponentMessageTypeLog ComponentMessageType = "log"
	ComponentMessageTypeStoreValueRequest ComponentMessageType = "storeValueRequest"
	ComponentMessageTypeLaunchUrlResponse ComponentMessageType = "launchUrlResponse"
	ComponentMessageTypeGetKeychainResponse ComponentMessageType = "getKeychainResponse"
	ComponentMessageTypeCompleteOauthAuthentication ComponentMessageType = "completeOauthAuthentication"
	ComponentMessageTypeLaunchUrlRequest ComponentMessageType = "launchUrlRequest"
	ComponentMessageTypeExecuteProgramResponse ComponentMessageType = "executeProgramResponse"
	ComponentMessageTypeCompleteSecretAuthentication ComponentMessageType = "completeSecretAuthentication"
	ComponentMessageTypeExecuteProgramRequest ComponentMessageType = "executeProgramRequest"
	ComponentMessageTypeStoreKeychainRequest ComponentMessageType = "storeKeychainRequest"
	ComponentMessageTypeSetup ComponentMessageType = "setup"
	ComponentMessageTypeRet ComponentMessageType = "ret"
	ComponentMessageTypeReady ComponentMessageType = "ready"
	ComponentMessageTypeHello ComponentMessageType = "hello"
	ComponentMessageTypeSendTrigger ComponentMessageType = "sendTrigger"
	ComponentMessageTypeExecute ComponentMessageType = "execute"
)

