// Generated by Passport. Do not modify.
// File generated at 3/4/2026, 11:08 AM
package hostio
import "time"
type HostMessageType string

const (
    HostMessageTypePermissionRequest HostMessageType = "permissionRequest"
	HostMessageTypeTaskRegistered HostMessageType = "taskRegistered"
	HostMessageTypeAuthorizationsList HostMessageType = "authorizationsList"
	HostMessageTypeCreateAuthorization HostMessageType = "createAuthorization"
	HostMessageTypeTaskTriggered HostMessageType = "taskTriggered"
	HostMessageTypeLogEvent HostMessageType = "logEvent"
	HostMessageTypeHello HostMessageType = "hello"
	HostMessageTypeComponentRegistered HostMessageType = "componentRegistered"
	HostMessageTypeGetAuthorizationsList HostMessageType = "getAuthorizationsList"
	HostMessageTypeRespondPermission HostMessageType = "respondPermission"
)

type HostMessageAuthorizationsList struct {
    Authorizations []HostMessageAuthorizationCreated `json:"authorizations"`
}

type HostMessageTaskRegistered struct {
    Name string `json:"name"`
	Url string `json:"url"`
}

type HostMessageComponentRegistered struct {
    Name string `json:"name"`
	Version string `json:"version"`
	Suceeded bool `json:"suceeded"`
	Path string `json:"path"`
	Error *string `json:"error"`
}

type HostMessageTaskTriggered struct {
    Id string `json:"id"`
	Name string `json:"name"`
	Date time.Time `json:"date"`
}

type HostMessageGetAuthorizationsList struct {
    
}

type HostMessageCreateAuthorization struct {
    Nickname string `json:"nickname"`
}

type HostMessageAuthorizationCreated struct {
    Nickname *string `json:"nickname"`
	Secret string `json:"secret"`
	Source string `json:"source"`
	CreatedDate time.Time `json:"created_date"`
}

type HostMessageLogEvent struct {
    Kind string `json:"kind"`
	Namespace string `json:"namespace"`
	Message string `json:"message"`
}

type HostMessageRequestPermission struct {
    Permission Permission `json:"permission"`
}

type HostMessageRespondPermission struct {
    Approve bool `json:"approve"`
}

