// Generated by Passport. Do not modify.
// File generated at 2/25/2026, 3:34 PM
package componentipc

type MessageType string

const (
	MessageTypeReady                MessageType = "ready"
	MessageTypeStoreValueRequest    MessageType = "storeValueRequest"
	MessageTypeExecute              MessageType = "execute"
	MessageTypeHello                MessageType = "hello"
	MessageTypeGetValueRequest      MessageType = "getValueRequest"
	MessageTypeGetKeychainRequest   MessageType = "getKeychainRequest"
	MessageTypeSetup                MessageType = "setup"
	MessageTypeRet                  MessageType = "ret"
	MessageTypeGetValueResponse     MessageType = "getValueResponse"
	MessageTypeStoreKeychainRequest MessageType = "storeKeychainRequest"
	MessageTypeLog                  MessageType = "log"
	MessageTypeGetKeychainResponse  MessageType = "getKeychainResponse"
)
