// Generated by Passport. Do not modify.
// File generated at 2/27/2026, 10:40 AM
package componentipc

type MessageType string

const (
    MessageTypeExecute MessageType = "execute"
	MessageTypeHello MessageType = "hello"
	MessageTypeRet MessageType = "ret"
	MessageTypeGetValueRequest MessageType = "getValueRequest"
	MessageTypeGetKeychainResponse MessageType = "getKeychainResponse"
	MessageTypeReady MessageType = "ready"
	MessageTypeSetup MessageType = "setup"
	MessageTypeLog MessageType = "log"
	MessageTypeStoreKeychainRequest MessageType = "storeKeychainRequest"
	MessageTypeGetValueResponse MessageType = "getValueResponse"
	MessageTypeStoreValueRequest MessageType = "storeValueRequest"
	MessageTypeGetKeychainRequest MessageType = "getKeychainRequest"
)

