// Generated by Passport. Do not modify.
// File generated at 2/26/2026, 3:07 PM
package componentipc

type MessageType string

const (
    MessageTypeRet MessageType = "ret"
	MessageTypeHello MessageType = "hello"
	MessageTypeStoreKeychainRequest MessageType = "storeKeychainRequest"
	MessageTypeGetValueRequest MessageType = "getValueRequest"
	MessageTypeLog MessageType = "log"
	MessageTypeGetValueResponse MessageType = "getValueResponse"
	MessageTypeSetup MessageType = "setup"
	MessageTypeReady MessageType = "ready"
	MessageTypeExecute MessageType = "execute"
	MessageTypeStoreValueRequest MessageType = "storeValueRequest"
	MessageTypeGetKeychainResponse MessageType = "getKeychainResponse"
	MessageTypeGetKeychainRequest MessageType = "getKeychainRequest"
)

